rm_sentry_pp_nocrc_serial:
  ros__parameters:
    port: /dev/sentry_vid200
    baud: 115200
    imu_frame: gimbal_big
    imu_parent_frame: chassis
    cmd_topic: cmd_vel_chassis
    imu_topic: gimbal_big/imu
    send_period_ms: 5
    enable_dtr_rts: true
    gimbal_lookahead_base: 0.3
    gimbal_follow_lookahead: 0.4
    gimbal_lookahead_k: 1.0
    gimbal_yaw_smooth_alpha: 0.05  # 0=非常平滑/迟缓，1=无滤波
    robot_area_name: bumpy_area
